#!/bin/sh
# Builds build/Slipstream.app from the Swift package and signs it ad hoc.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
CONFIGURATION=${CONFIGURATION:-release}
APP="$ROOT/build/Slipstream.app"

swift build --package-path "$ROOT" -c "$CONFIGURATION" --arch arm64
BINARY=$(swift build --package-path "$ROOT" -c "$CONFIGURATION" --arch arm64 --show-bin-path)/SlipstreamMenubar

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BINARY" "$APP/Contents/MacOS/SlipstreamMenubar"
cp "$ROOT/Resources/Info.plist" "$APP/Contents/Info.plist"
# Generated by scripts/make-icon.swift from the bolt; committed so builds need no drawing.
cp "$ROOT/Resources/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
# The model manifest: what setup and Settings offer (ModelManifest.bundled).
cp "$ROOT/Resources/models.json" "$APP/Contents/Resources/models.json"
# The version users see (Finder's Get Info, About): MARKETING_VERSION when the
# release workflow passes it, otherwise the latest vYY.MM.N tag. The build number
# is the commit.
VERSION=${MARKETING_VERSION:-$(git -C "$ROOT" describe --tags --abbrev=0 --match 'v[0-9]*' 2>/dev/null | sed 's/^v//')}
BUILD=$(git -C "$ROOT" describe --always --dirty 2>/dev/null || echo dev)
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${VERSION:-0.0.0}" "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$APP/Contents/Info.plist"
codesign --force --sign - --options runtime "$APP"
echo "$APP"
